apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vote
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - image: optumera.icp:8500/default/vote:0.1.0
        name: vote
        imagePullPolicy: IfNotPresent
      imagePullSecrets:
        - name: registry-secret
