apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: optumera.icp:8500/default/worker:0.1.0
        name: worker
        imagePullPolicy: IfNotPresent
      imagePullSecrets:
        - name: registry-secret
